//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelleryShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeTable
    {
        public int Employee_Id { get; set; }
        public string EmployeeUserName { get; set; }
        public string EmployeePwd { get; set; }
        public string EmployeeImage { get; set; }
        public string EmployeeContact { get; set; }
        public Nullable<int> roleId { get; set; }
    
        public virtual RolesTable RolesTable { get; set; }
    }
}
