//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelleryShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordered_Products
    {
        public int OP_Id { get; set; }
        public Nullable<int> orderId { get; set; }
        public Nullable<int> productId { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> price { get; set; }
    
        public virtual OrdersTable OrdersTable { get; set; }
        public virtual ProductsTable ProductsTable { get; set; }
    }
}
