//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JewelleryShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrdersTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrdersTable()
        {
            this.Ordered_Products = new HashSet<Ordered_Products>();
        }
    
        public int orderId { get; set; }
        public Nullable<int> userId { get; set; }
        public Nullable<System.DateTime> placementDate { get; set; }
        public Nullable<System.DateTime> deliveryData { get; set; }
        public string isDelievered { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ordered_Products> Ordered_Products { get; set; }
        public virtual UsersTable UsersTable { get; set; }
    }
}
